global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "127.0.0.1:9090"

  - job_name: node-exporter
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          machine_name: fedispace-1

  - job_name: docker-stats
    static_configs:
    - targets: ['host.docker.internal:9323']
      labels:
        alias: 'docker-stats'

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: 'yace-exporter'
    static_configs:
      - targets: ['yace-exporter:5000']