# Databases Stack

version: '3.3'
services:
    postgresql:
      restart: always
      image: postgres:15.4
      networks:
        - databases-net
        - external-net
      ports: 
        - 5432:5432
      volumes: 
        - '/data/databases/postgres:/var/lib/postgres'

    # redis:
    #   restart: always
    #   image:
    #   ports:
    #     - 
    #   networks:
    #     - databases-net

networks:
  external-net:
  databases-net:
    internal: true