# Databases Stack

version: '3.3'
services:
    postgresql:
      restart: always
      image: postgres:15.4
      networks:
        - internal-net
        - external-net
      ports: 
        - 127.0.0.1:5432:5432
      volumes: 
        - '/data/databases/postgresql/data/:/var/lib/postgresql/data/'
      environment:
        - POSTGRES_USER=
        - POSTGRES_PASSWORD=

    redis:
      restart: always
      image: redis:latest
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - 127.0.0.1:6379:6379
      networks:
        - internal-net
        - external-net
      volumes:
        - './config/redis/redis.conf:/usr/local/etc/redis/redis.conf'
        - '/data/databases/redis/data/:/data'

networks:
  external-net:
  internal-net:
    internal: true