# Reverse Proxy

version: '3.3'
services:
  reverse-proxy:
    restart: always
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - internal-net
      - monitoring_internal-net
      - external-net
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    - /data/reverse-proxy/certbot/conf:/etc/letsencrypt
    - /data/reverse-proxy/certbot/www:/var/www/certbot
    - /data/fediland-website:/var/www/fediland-website

  certbot:
    restart: always
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /data/reverse-proxy/certbot/conf:/etc/letsencrypt
      - /data/reverse-proxy/certbot/www:/var/www/certbot

networks:
  external-net:
  internal-net:
    internal: true
  monitoring_internal-net:
    external: true